---
# tasks file for ansible-rsyncbackup

# Configure a script to backup folders to a rsync server
# list of folders to backup should be added to {{ rsyncbackup_conf }}

- name: create configuration file
  become: yes
  template:
    src: backup.conf.j2
    dest: "{{ rsyncbackup_conf }}"
    owner: "{{ rsyncbackup_localuser }}"
    group: "{{ rsyncbackup_localuser }}"
    mode: 0644

- name: create log file
  become: yes
  file:
    dest: /var/log/backup.log
    owner: "{{ rsyncbackup_localuser }}"
    group: "{{ rsyncbackup_localuser }}"
    mode: 0664
    state: touch

- name: upload backup script
  become: yes
  template:
    src: backup.sh.j2
    dest: /usr/bin/backup.sh
    owner: "{{ rsyncbackup_localuser }}"
    group: "{{ rsyncbackup_localuser }}"
    mode: 0755

- name: create backup cron job
  become: yes
  cron:
    name: "Backup"
    user: "{{ rsyncbackup_localuser }}"
    hour: "{{ rsyncbackup_hour }}"
    minute: "{{ rsyncbackup_min }}"
    job: "/usr/bin/backup.sh"
    state: present
