---
# tasks file for ansible-rsyncbackup

# Configure a script to backup folders to a rsync server
# list of folders to backup should be added to {{ rsyncbackup_conf }}

- name: create conf file
  sudo: yes
  file: dest={{ rsyncbackup_conf }} owner={{ rsyncbackup_localuser }} group={{ rsyncbackup_localuser }} mode=0644 state=touch

- name: create log file
  sudo: yes
  file: dest=/var/log/backup.log owner={{ rsyncbackup_localuser }} group={{ rsyncbackup_localuser }} mode=0664 state=touch

- name: upload backup script
  sudo: yes
  template: src=backup.sh.j2 dest=/usr/bin/backup.sh owner={{ rsyncbackup_localuser }} group={{ rsyncbackup_localuser }} mode=0755

- name: create backup cron job
  sudo: yes
  cron: name="Backup" user="{{ rsyncbackup_localuser }}" hour="{{ rsyncbackup_hour }}" minute="{{ rsyncbackup_min }}" job="/usr/bin/backup.sh" state=present
